### ISSUE TITLE
Parametrization + `into PerVertex UV` produces invalid meshes in Meshlab 2021.05d

### ISSUE THREAD

**Issue by nh2** [cnr-isti-vclab/meshlab#1113]
For mesh

https://nh2.me/mesh-crashing-meshlab-when-flatplaned-and-per-vertex-uvd.ply

With Meshlab 2021.05d the following steps will make Meshlab produce save a mesh that cannot be reopened in Meshlab itself; it will produce `Bad vertex index in face`:

* Open the mesh linked above
* `Parametrization: Flat Plane`, keep default settings (XY) (`Trivial Per-Triangle` also results in the error)
* `Convert PerWedge UV into PerVertex UV`, keep default settings
* File -> `Export mesh as`, save as `bad-mesh.ply` with these settings: 
![image](https://user-images.githubusercontent.com/399535/136716707-681e86fd-eeef-48ee-884c-3fc681411750.png)
* Re-open that saved PLY in Meshlab. You will get `Bad vertex index in face`: 
![image](https://user-images.githubusercontent.com/399535/136716833-c93cefe4-77cc-487a-bfaa-17899061b677.png)

This issue does **not* happen with Meshlab 2020.12, which creates valid outputs from the same input and the instructions above.

**Comment by alemuntoni** [comment]
Just to be sure:
- does the issue happen on 2021.07?
> MeshLab_64bit_fp v2021.10
- is **2021.10** a typo? Do you mean the 2021.10 nightly version? Because if it is not a typo, I just don't understand why did you open this issue: if 2021.10 nightly works, it just means that the issue has been already solved....

**Comment by nh2** [comment]
> * is **2021.10** a typo?

Sorry, it's not a typo, but it's still unintended. It is this commit of Meshlab (a 2019 version): 25f3d17b1d1d47ddc51179cb955f3027b7638745

But it is an older build that was not yet fixed to not put the build date into the info screen.

> does the issue happen on 2021.07?

I have not tried that yet, I've tried only on the versions I have immediately access to.

**Comment by alemuntoni** [comment]
confirmed also in 2021.07d. It affects only double precision versions due to the floating point precision used for uv vertex texcoords

**Comment by nh2** [comment]
Thank you!
