### ISSUE TITLE
u3d export only tex file created

### ISSUE THREAD

**Issue by ferdymercury** [cnr-isti-vclab/meshlab#495]
U3D export fails silently. Consider attached test ply file.
[test.ply.zip](https://github.com/cnr-isti-vclab/meshlab/files/3826680/test.ply.zip)

If I export it as U3D, I get the message:
`Saved Mesh test.u3d in 115 msec`

However, only test.tex is created, not test.u3d

If I run Meshlab through terminal, i get the message: 'saved 0 meshes'. I think a popup warning should be given if U3D export 'succeeds' but does not write a file because there are no meshes found.

I tried resaving the .ply file with Meshlab and reimporting, but same result.

With the same example file, if I do Compute Normals for Point Sets, Screened Surface Poisson reconstruction, Depth 8, and then (important!) DELETE the original data  from the 'layers' dialog, export the new data as u3d, then the U3D export works fine and a .u3d file is created. Tested that this is reproducible in Windows and Mac, 2016.12 version  [EDIT: In new Meshlab version, do instead Filters, Remeshing, Surface Reconstruction Screened Poisson. Now need for deleting then any layer.].

Ideally, one would expect Meshlab to give a warning in the first place that no u3d export is possible if just a cloud of points, instead of silently 'succeeding'.

Might be related with:
https://github.com/cnr-isti-vclab/meshlab/issues/192
https://github.com/cnr-isti-vclab/meshlab/issues/153
https://github.com/cnr-isti-vclab/meshlab/issues/33
https://github.com/cnr-isti-vclab/meshlab/issues/228
https://github.com/cnr-isti-vclab/meshlab/issues/61

**Comment by nmenu** [comment]
On windows 10 , I do have the same problem on meshlab 64bit_fp_v2016.12.

Import an OBJ textured file in mesh lab
Export mesh as ud3... I get a message that the exporter is not available... so I copied the U3D_OSX and U3D_W32 folder into the meshlab pluging folder and restart meshlab.

Now the exporter seems to work, but only the .tex file is created

**Comment by alemuntoni** [comment]
Hi, could you please try with MeshLab 2020.02?
You can find the installer [here](https://github.com/cnr-isti-vclab/meshlab/releases).
Let me know if it works, and if not, can you plase share the obj file you used?

**Comment by nmenu** [comment]
Hi alemuntoni,
Same issue with 2020.02 ... just tested. Only the .tex is created.

You can test with those files... 
https://drive.google.com/open?id=1umUIU6baiLwyHiCu-X8lg7lbdvPMd6xQ

Thanks

**Comment by ferdymercury** [comment]
Run meshlab from terminal and see what log messages are printed. I had the same issue, see my comment above where I preprocessed the file.

**Comment by alemuntoni** [comment]
Hi, I tested the mesh and the problem here is related the converter we use to save U3D files, which is https://github.com/ningfei/u3d. 
With linux, trying to convert the obj @nmenu uploaded (after saved in IDTF format), I get:
```
$ IDTFConverter -en 1 -rzf 0 -pq 500 -input "CharbonP1recap.idtf" -output "CharbonP1recap.u3d"
> Exit code = 80000003
```
Something goes wrong with the converter, and I believe the same happens also with Windows. I still have to check if the idtf file saved by meshlab is valid.

**Comment by martin-stastny** [comment]
Hello, I have tried version 2020.3 and the problem is still unsolved, is anyone working on solution, or is there some HOTFIX?
Output:
`Exit code = 80000003`

**Comment by ferdymercury** [comment]
Did you try preprocessing the file before exporting? See https://github.com/cnr-isti-vclab/meshlab/issues/495#issue-520288621

**Comment by ejjunju** [comment]
I have the exact problem. I downloaded the current version of MeshLab_64bit_fp v2020.02   (built on Feb 17 2020). I created volcano.stl file using R and successfully imported in into Meshlab. Then i exported as volcano.ply which went well. I reimported the the volcano.ply file and exported as volcano.u3d. i got the message that volcano.u3d was exported in 1007 ms. But only the volcano.tex file was created; there was no u3d file.  Attached are my volcano.ply and volcano.stl files (
[volcano.zip](https://github.com/cnr-isti-vclab/meshlab/files/4307434/volcano.zip)
zipped)

**Comment by salazar23** [comment]
+1 ... same here: tex-file created, but no u3d-file

**Comment by worm6666** [comment]
try this - put in plugins folder - rename all existing u3d folders to some other name

[U3D plugins for Meshlab 2020_03.zip](https://github.com/cnr-isti-vclab/meshlab/files/4434385/U3D.plugins.for.Meshlab.2020_03.zip)

[3D Model.pdf](https://github.com/cnr-isti-vclab/meshlab/files/4434388/3D.Model.pdf)

**Comment by worm6666** [comment]
if meshlab fails to start on latest windows 10 - uninstall all MS Visual C++ 2015 redistributables, reinstall Meshlab - works now :-)

- it fires in EventLog error about missing ucrtbase.dll - it is MSVC 2015 problem...

**Comment by martin-stastny** [comment]
Everything is working just fine, haven't even encountered MSVC issue. 

Great job!

I have only one suggestion, to use newer latex library for u3d import, media9, but I guess it isn't crucial concern of yours.

**Comment by CsatiZoltan** [comment]
Same symptom: .tex file generated but no .u3d file. Using the latest Appimage version under Ubuntu 18.04.

```bash
U3D plugins dir /tmp/.mount_MeshLaJUjZws/usr/lib/meshlab/plugins/U3D_LINUX
conv_loc_st '/tmp/.mount_MeshLaJUjZws/usr/lib/meshlab/plugins/U3D_LINUX/bin/IDTFConverter'
conv_loc '/tmp/.mount_MeshLaJUjZws/usr/lib/meshlab/plugins/U3D_LINUX/bin/IDTFConverter'
idtfpar._converter_loc '/tmp/.mount_MeshLaJUjZws/usr/lib/meshlab/plugins/U3D_LINUX/bin/IDTFConverter'
Starting converter /tmp/.mount_MeshLaJUjZws/usr/lib/meshlab/plugins/U3D_LINUX/bin/IDTFConverter -en 1 -rzf 0 -pq 500 -input "/tmp/elastoplastic_extended_physical_2.u3d.idtf" -output "/home/zoltan/Programs/elastoplastic_extended_physical_2.u3d"
LOG: 0 Saved Mesh /home/zoltan/Programs/elastoplastic_extended_physical_2.u3d in 206 msec
```

**Comment by ferdymercury** [comment]
related https://github.com/cnr-isti-vclab/meshlab/issues/666

**Comment by CsatiZoltan** [comment]
@ferdymercury I saw it, but the solutions only concern Windows.

**Comment by FreyaGoetz** [comment]
I have the same issue. I'm on a mac. I used this program on this computer last fall (not sure which version) and it worked just fine. Today I updated to the latest version and I'm getting a .tex file with no .u3d.

**Comment by FreyaGoetz** [comment]
Thank you!
Unfortunately the .dmg file I downloaded from the actions tab didn’t help. I would say that maybe I’m doing something wrong, but I used this program to convert a bunch of .ply to .u3d last fall and had no problems.

Freya

On Jun 5, 2020, at 3:10 PM, Alessandro Muntoni <notifications@github.com<mailto:notifications@github.com>> wrote:

External Email - Exercise Caution


This issue should be solved on #713<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnr-isti-vclab%2Fmeshlab%2Fpull%2F713&data=02%7C01%7Cgoetzf%40si.edu%7C2856b0464f94446d9f4708d809840ff2%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637269810091433789&sdata=iVtriVywRXG7zskA213goEtjm0l%2Bog8bG6A76BuLOqQ%3D&reserved=0>. You can test the u3d exporter by downloading the artifacts from the github actions tab (windows<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnr-isti-vclab%2Fmeshlab%2Factions%2Fruns%2F126283313&data=02%7C01%7Cgoetzf%40si.edu%7C2856b0464f94446d9f4708d809840ff2%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637269810091443785&sdata=DQYUhnW46bqvBbBZdONGD%2Fzl74rZlILO5p5YMIQKjBQ%3D&reserved=0>, mac<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnr-isti-vclab%2Fmeshlab%2Factions%2Fruns%2F126283305&data=02%7C01%7Cgoetzf%40si.edu%7C2856b0464f94446d9f4708d809840ff2%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637269810091453778&sdata=0dxDIppX2WUz2zhQEnQePNnwGCwcnTlREBqmtNH1sHY%3D&reserved=0>, linux<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcnr-isti-vclab%2Fmeshlab%2Factions%2Fruns%2F126283309&data=02%7C01%7Cgoetzf%40si.edu%7C2856b0464f94446d9f4708d809840ff2%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637269810091453778&sdata=2lgte9svKkm4Zsmfm6x0F04B%2FEyfAy7JfRC6rIKy1Vs%3D&reserved=0>). The fix will be available starting from version 2020.07.

**Comment by ferdymercury** [comment]
Did you try this? Maybe it helps:
"Compute Normals for Point Sets, Screened Surface Poisson reconstruction, Depth 8, and then (important!) DELETE the original data from the 'layers' dialog, export the new data as u3d"

**Comment by alemuntoni** [comment]
Could you provide a file that is still not working? 
And could you try if a simple mesh works? For example: Filters -> Create new mesh layer -> Dodecahedron, and then export to .u3d.

We are using an external tool for exporting u3d ([this one](https://github.com/ningfei/u3d)) and the issue could be related to this external tool.

**Comment by CsatiZoltan** [comment]
@alemuntoni I downloaded the [AppImage](https://github.com/cnr-isti-vclab/meshlab/suites/761140102/artifacts/7905599) from the site you gave, created the dodecahedron, exported to .u3d, and still only got the .tex file:
```latex
\documentclass[a4paper]{article}
\usepackage[3D]{movie15}
\usepackage{hyperref}
\usepackage[UKenglish]{babel}
\begin{document}
\includemovie[
	poster,
	toolbar, %same as `controls'
	label=Transfer.u3d,
	text=(Transfer.u3d),
	3Daac=60.000000, 3Droll=0.000000, 3Dc2c=0.000000 -14.670000 0.000000, 3Droo=14.670000, 3Dcoo=-0.000000 0.000000 0.000000,
	3Dlights=CAD,
]{\linewidth}{\linewidth}{Transfer.u3d}
\end{document}

```

**Comment by FreyaGoetz** [comment]
Here is the file I’m using. I didn’t fully understand this instruction: "Compute Normals for Point Sets, Screened Surface Poisson reconstruction, Depth 8, and then (important!) DELETE the original data from the 'layers' dialog, export the new data as u3d”

I’ll try the simple mesh suggestion now. I honestly was only using your program to save the volume as U3D so I don’t know Meshlab very well.

Freya

On Jun 6, 2020, at 4:16 AM, Alessandro Muntoni <notifications@github.com<mailto:notifications@github.com>> wrote:


External Email - Exercise Caution


Could you provide a file that is still not working?
And could you try if a simple mesh works? For example: Filters -> Create new mesh layer -> Dodecahedron, and then export to .u3d.

We are using an external tool for exporting u3d (this one<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fningfei%2Fu3d&data=02%7C01%7Cgoetzf%40si.edu%7Ca1103f170b0445fdb25108d809f1db71%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637270281663171095&sdata=qESaP7j5dlejlTKdm3HdWnAE1poMS97EkuL%2FgYH6bTI%3D&reserved=0>) and the issue could be related to this external tool.

**Comment by ferdymercury** [comment]
Once you open the Mesh file, click on the top bar on Filters, Normals, Compute Normal Points for point sets.
After this, in some older versions of Meshlab, you can select Screened Surface Poisson reconstruction, Depth 8. If not, just leave the default options. Click Apply.
Then, you can click in View Layer Dialogs. In some versions, you have the old and the new dataset on the right menu. If yes, delete the old one.
Finally click export as u3d.
Following these steps solved the issue to me in one of my files that was missing the u3d.

**Comment by FreyaGoetz** [comment]
Thank you for the more detailed instructions. Unfortunately, it didn’t work for me.

The files are going directly to my local dropbox folder, but since it’s local, I thought it wouldn’t affect things.

On Jun 8, 2020, at 10:20 AM, ferdymercury <notifications@github.com<mailto:notifications@github.com>> wrote:

External Email - Exercise Caution


Once you open the Mesh file, click on the top bar on Filters, Normals, Compute Normal Points for point sets.
After this, in some older versions of Meshlab, you can select Screened Surface Poisson reconstruction, Depth 8. If not, just leave the default options. Click Apply.
Then, you can click in View Layer Dialogs. In some versions, you have the old and the new dataset on the right menu. If yes, delete the old one.
Finally click export as u3d.
Following these steps solved the issue to me in one of my files that was missing the u3d.

**Comment by alemuntoni** [comment]
Hi all,
I am working on a solution that will resolve all the issues related with u3d once for all. I'm going to change the organization of the u3d exporter (which is now an orrible binary placed as a plugin inside the meshlab folder). This will allow also to manage errors and give proper feedbacks.

I hope to finish in the next days. I'll write here when it is ready.

**Comment by FreyaGoetz** [comment]
Wonderful! Thank you so much!

Freya
________________________________

**Comment by alemuntoni** [comment]
Hi all, 
with #726 the u3d exporter should now work on every platform.
All the built packages will be available soon in the [github actions tab](https://github.com/cnr-isti-vclab/meshlab/actions). Please test them and leave here a comment if everything works!
The exporter will be included in the next 2020.07 version!

**Comment by CsatiZoltan** [comment]
I tried the [latest Appimage](https://github.com/cnr-isti-vclab/meshlab/suites/813738228/artifacts/8905221), which now generates the u3d file. Unfortunately, neither Evince nor Okular supports u3d. As far as I know, only Adobe Reader can open it. I installed the [latest version](https://askubuntu.com/questions/471561/how-to-view-3d-pdf-files) available for Ubuntu, and I could successfully open it. Thanks a lot!

![u3d](https://user-images.githubusercontent.com/12742890/85048025-fb703d80-b192-11ea-80bc-5a661373900c.gif)

**Comment by ferdymercury** [comment]
> I tried the [latest Appimage](https://github.com/cnr-isti-vclab/meshlab/suites/813738228/artifacts/8905221), which now generates the u3d file. Unfortunately, neither Evince nor Okular supports u3d. As far as I know, only Adobe Reader can open it. I installed the [latest version](https://askubuntu.com/questions/471561/how-to-view-3d-pdf-files) available for Ubuntu, and I could successfully open it. Thanks a lot!
> 
> ![u3d](https://user-images.githubusercontent.com/12742890/85048025-fb703d80-b192-11ea-80bc-5a661373900c.gif)

There are some ideas to natively support 3D PDF files in Linux, but none of them has been yet developed:
https://github.com/vectorgraphics/asymptote/issues/167
https://tracker.freecadweb.org/view.php?id=4403

**Comment by ferdymercury** [comment]
> Hi all,
> with #726 the u3d exporter should now work on every platform.
> All the built packages will be available soon in the [github actions tab](https://github.com/cnr-isti-vclab/meshlab/actions) (run number 29). Please test them and leave here a comment if everything works!
> The exporter will be included in the next 2020.07 version!

I downloaded the 2020.07 AppImage on Ubuntu 18, and it does not work for me. I get the following errors with the test.ply file of my first post:

![image](https://user-images.githubusercontent.com/10653970/90423622-cbf28a00-e08a-11ea-8326-14915631c6c1.png)

Do I need to install the IDTFConverter somehow separately?

```
LOG: 0 Opened mesh /tmp/test.ply in 244 msec
LOG: 0 All files opened in 245 msec
QLayout: Attempting to add QLayout "" to SaveMaskExporterDialog "MaskExporterDialog", which already has a layout

Profile = 0
Scaling factor = 1.000000
Debug level = 0
Position Quality = 500
Texture Coordinate Quality = 1000
Normal Quality = 1000
Diffuse Color Quality = 1000
Specular Color  Quality = 1000
Geometry Default Quality = 1000
Texture Quality = 100
Animation Quality = 1000
Zero Area Faces Removal = DISABLED
Exclude Normals = TRUE
Export Option Flags = ffff
Texture size limit = 0

Exit code = 81110002
LOG: 0 Error Saving Mesh /tmp/test.u3d
```
